<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-QCVUE6B" failures="4" tests="5" name="EdgeTest" time="25.913" errors="0" timestamp="2024-07-13T15:45:55 IST">
  <testcase classname="test.Test_LoginScenario1" name="verifyUserCanLogin" time="4.144">
    <failure type="java.lang.AssertionError" message="Login Fail expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Fail expected [true] but found [false]
at pages.LoginPage.verifyLoginwithCredentials(LoginPage.java:45)
at test.Test_LoginScenario1.verifyUserCanLogin(Test_LoginScenario1.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanLogin -->
  <testcase classname="test.Test_LoginScenario1" name="verifyUserCanLogin" time="3.138">
    <failure type="java.lang.AssertionError" message="Login Fail expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Fail expected [true] but found [false]
at pages.LoginPage.verifyLoginwithCredentials(LoginPage.java:45)
at test.Test_LoginScenario1.verifyUserCanLogin(Test_LoginScenario1.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanLogin -->
  <testcase classname="test.Test_LoginScenario1" name="verifyUserCanLogin" time="3.174">
    <failure type="java.lang.AssertionError" message="Login Fail expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Fail expected [true] but found [false]
at pages.LoginPage.verifyLoginwithCredentials(LoginPage.java:45)
at test.Test_LoginScenario1.verifyUserCanLogin(Test_LoginScenario1.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanLogin -->
  <testcase classname="test.Test_LoginScenario1" name="verifyUserCanLogin" time="3.563">
    <failure type="java.lang.AssertionError" message="Login Fail expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Fail expected [true] but found [false]
at pages.LoginPage.verifyLoginwithCredentials(LoginPage.java:45)
at test.Test_LoginScenario1.verifyUserCanLogin(Test_LoginScenario1.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanLogin -->
  <testcase classname="test.Test_LoginScenario1" name="verifyUserCanLogin" time="3.909"/>
</testsuite> <!-- EdgeTest -->
